name: Deploy Supabase Functions
on:
  push:
    branches: [main]
    paths: ['supabase/functions/**', 'supabase/migrations/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: llsjysvklkohnzgmpyob
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy migrations
        run: |
          supabase db push --project-ref $PROJECT_ID
          
      - name: Deploy all functions
        run: |
          supabase functions deploy --project-ref $PROJECT_ID 