name: Deploy Supabase Functions
on:
  push:
    branches: [main]
    paths: ['supabase/functions/**', 'supabase/migrations/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Link project
        run: |
          supabase link --project-ref llsjysvklkohnzgmpyob
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
      - name: Deploy migrations
        run: |
          supabase db push --linked
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
      - name: Deploy functions
        run: |
          supabase functions deploy generate_summary --linked
          supabase functions deploy telegram_webhook --linked
          supabase functions deploy ingest_telegram_message --linked
          supabase functions deploy ingest_telegram_saved --linked
          supabase functions deploy syncTelegramMessage --linked
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} 